apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- range $key, $value := .Values.labels }}
      {{ $key }}: {{ $value  }}
    {{- end }}
  template:
    metadata:
      labels:
      {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
             cpu: {{ .Values.resources.requests.cpu }}
             memory: {{ .Values.resources.requests.memory }}
            limits:
             cpu: {{ .Values.resources.limits.cpu }} 
             memory: {{ .Values.resources.limits.memory }} 
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1  
  
         
