apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  annotations: 
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- range $key, $value := .Values.selector }}
    {{ $key }}: {{ $value }}
  {{- end }}
    